trigger:
- main

pool:
  name: 'Default'   # or your custom agent pool name

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build Application'

- script: |
    echo "Running Tests"
  displayName: 'Test Application'

- script: |
    echo "Deploying App"
  displayName: 'Deploy Step'
